Use Cassandra for ShortCircuit results in CIMWeb
    Fix shortcircuit schema to only use one table for results, we don't want to make the same mistake with Nullungsbedingung table.
    Update short circuit RESTful service to return primary key of Cassandra storage.
    Remove PseudoScResult.
    Update analysis javascript to use Cassandra output
    Update the analysis theme based on the Cassandra query.

diff --git a/tinymake-docker b/tinymake-docker
--- a/tinymake-docker
+++ b/tinymake-docker
@@ -23,4 +23,10 @@ fi
 
 set -x
 # mvn clean dependency:purge-local-repository;
-mvn clean -Dmaven.test.skip=true -DskipTests -DskipITs --projects CIMConnector,CIMWeb,CIMEar install; docker build --quiet --file ${AppServer}.Dockerfile --tag derrickoswald/cimapplication:${Tag} .;docker tag derrickoswald/cimapplication:${Tag} derrickoswald/cimapplication:latest
+mvn clean -Dmaven.test.skip=true -DskipTests -DskipITs --projects CIMConnector,CIMWeb,CIMEar install
+STATUS=$?
+if [ $STATUS -eq 0 ]; then
+docker build --quiet --file ${AppServer}.Dockerfile --tag derrickoswald/cimapplication:${Tag} .;docker tag derrickoswald/cimapplication:${Tag} derrickoswald/cimapplication:latest
+else
+echo "Maven failed"
+fi
